version: '3.8'

services:
  recruitment-front:
    image: suryaa112003/recruitment-app:v1.1.1
    container_name: recruitment-frontend
    ports:
      - "83:3000"
    networks:
      - recruitment-network
    environment:
      - MONGO_URI=mongodb://rootuser:rootpassword@mongodb:27017/hr_system?authSource=rootuser
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - recruitment-network
    volumes:
      - recruitment-volume:/data/db
  
volumes:
  recruitment-volume:
networks:
  recruitment-network: