
version: '3.8'

services:
  recruitment-front:
    image: suryaa112003/recruitment-app:v1.1.1
    container_name: recruitment-frontend
    ports:
      - "83:3000"
    networks:
      - recruitment-network1
    environment:
      - MONGO_URI=mongodb://rootuser:rootpassword@common:27017/hr_system?authSource=admin
  
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - recruitment-network2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
  common:
    image: nginx
    container_name: common
    ports: "88:8080"
    networks:
      - recruitment-network1
      - recruitment-network2
    volumes:
      - ./nginx.config:/etc/nginx/nginx.config
  

networks:
  recruitment-network1:
  recruitment-network2:
